spring:
  application:
    name: bus-service
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    username: bus
    password: bus123
    url: jdbc:h2:mem:dbbus
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8871/eureka
