spring:
  application:
    name: eureka-server

server:
  port: 8871

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
      enableSelfPreservation: false
